import React, { useEffect, useMemo, useState } from 'react';
import { BookOpen, CalendarDays, Check, CheckCircle2, ChevronDown, ChevronLeft, ChevronRight, Circle, Clock3, FileText, Flame, GraduationCap, Layers3, MoreHorizontal, Palette, Play, Plus, Search, Sparkles, TimerReset, Trash2, X } from 'lucide-react';
import { SubjectItem, TaskItem } from '../types/konkur';
import { addDays, addDaysToJalaliKey, dateToJalaliKey, formatJalaliKey, formatJalaliKeyWithWeekday, jalaliKeyToDate, minutesToTime, normalizeTime, parseJalaliKey, PERSIAN_MONTHS, PERSIAN_WEEKDAYS, timeToMinutes, todayJalaliKey, toPersianDigits } from '../utils/jalali';
import { tasksForDay } from '../utils/stats';

interface Props { tasks:TaskItem[]; subjects:SubjectItem[]; onToggleTask:(id:string)=>void; onAddTask:(task:Omit<TaskItem,'id'>)=>void; onDeleteTask:(id:string)=>void; onStartFocus:(name:string)=>void; autoOpenAdd?:boolean; onAutoOpenAddHandled?:()=>void }
type ActivityType='study'|'class'|'other'; type TimeMode='range'|'duration';
const COLORS=['#6D5DFB','#FF6B3D','#1D9BF0','#12B76A','#F2B705','#EA3B8B'];
const CHAPTERS:Record<string,string[]>={
 'زیست‌شناسی':['مولکول‌های اطلاعاتی','جریان اطلاعات در یاخته','انتقال اطلاعات در نسل‌ها','تغییر در اطلاعات وراثتی','از ماده به انرژی','از انرژی به ماده'],
 'شیمی':['قدر هدایای زمینی را بدانیم','در پی غذای سالم','پوشاک، نیازی پایان‌ناپذیر','مولکول‌ها در خدمت تندرستی'],
 'فیزیک':['حرکت بر خط راست','دینامیک و حرکت دایره‌ای','نوسان و موج','فیزیک اتمی و هسته‌ای'],
 'حسابان و دیفرانسیل':['هندسه تحلیلی و جبر','هندسه','تابع','مثلثات','توابع نمایی و لگاریتمی','حد و پیوستگی','مشتق'],
 'ریاضیات تجربی':['تابع','مثلثات','حد و پیوستگی','مشتق','کاربرد مشتق','احتمال'],
 'هندسه':['ماتریس و کاربردها','مقاطع مخروطی','بردارها','تجسم فضایی'],
 'گسسته و آمار':['نظریه اعداد','گراف و مدل‌سازی','ترکیبیات','احتمال'],
 'ادبیات فارسی':['ستایش و نیایش','ادبیات تعلیمی','ادبیات پایداری','ادبیات غنایی','ادبیات سفر و زندگی'],
 'عربی':['ترجمه و تعریب','قواعد فعل','اسم و مشتقات','درک مطلب'],
 'دین و زندگی':['هستی‌بخش','یگانه بی‌همتا','توحید و سبک زندگی','قدرت پرواز','سنت‌های خداوند'],
 'زبان انگلیسی':['Sense of Appreciation','Look it Up','Renewable Energy','Traveling the World']
};
const GENERIC=['فصل اول','فصل دوم','فصل سوم','فصل چهارم','فصل پنجم','جمع‌بندی و مرور'];
const durationLabel=(m:number)=>{const h=Math.floor(m/60),r=m%60;return h?(r?`${toPersianDigits(h)} ساعت و ${toPersianDigits(r)} دقیقه`:`${toPersianDigits(h)} ساعت`):`${toPersianDigits(r)} دقیقه`};
const dayName=(key:string)=>{const d=jalaliKeyToDate(key);return d?PERSIAN_WEEKDAYS[d.getDay()]:''};

export const CalendarView:React.FC<Props>=({tasks,subjects,onToggleTask,onAddTask,onDeleteTask,onStartFocus,autoOpenAdd=false,onAutoOpenAddHandled})=>{
 const today=todayJalaliKey(); const [selectedDate,setSelectedDate]=useState(today); const [weekAnchor,setWeekAnchor]=useState(today); const [monthOpen,setMonthOpen]=useState(false); const [formOpen,setFormOpen]=useState(false); const [menu,setMenu]=useState<string|null>(null);
 const dayTasks=useMemo(()=>tasksForDay(tasks,selectedDate),[tasks,selectedDate]);
 const week=useMemo(()=>{const anchor=jalaliKeyToDate(weekAnchor)??new Date();const saturday=addDays(anchor,-((anchor.getDay()+1)%7));return Array.from({length:7},(_,i)=>dateToJalaliKey(addDays(saturday,i)))},[weekAnchor]);
 const meta=parseJalaliKey(selectedDate), done=dayTasks.filter(t=>t.isCompleted).length, total=dayTasks.reduce((n,t)=>n+t.durationMinutes,0);
 useEffect(()=>{if(autoOpenAdd){setSelectedDate(today);setWeekAnchor(today);setFormOpen(true);onAutoOpenAddHandled?.()}},[autoOpenAdd,onAutoOpenAddHandled,today]);
 if(!subjects.length)return <div className="calendar-empty" dir="rtl"><GraduationCap/><strong>اول درس‌هایت را بساز</strong><span>از تنظیمات رشته را انتخاب کن، بعد تقویمت آماده است.</span></div>;
 return <section className="calendar-page" dir="rtl">
  <div className="calendar-heading"><div><span className="calendar-eyebrow"><Sparkles/> برنامه‌ی مطالعه</span><h1>تقویم</h1></div><button className="calendar-today-btn" onClick={()=>{setSelectedDate(today);setWeekAnchor(today)}}>امروز</button></div>
  <div className="calendar-month-row"><button onClick={()=>setWeekAnchor(addDaysToJalaliKey(weekAnchor,7))}><ChevronRight/></button><button className="calendar-month-title" onClick={()=>setMonthOpen(v=>!v)}>{meta?`${PERSIAN_MONTHS[meta.jm-1]} ${toPersianDigits(meta.jy)}`:''}<ChevronDown className={monthOpen?'rotated':''}/></button><button onClick={()=>setWeekAnchor(addDaysToJalaliKey(weekAnchor,-7))}><ChevronLeft/></button></div>
  {monthOpen&&meta?<MonthPicker year={meta.jy} month={meta.jm} selected={selectedDate} tasks={tasks} onSelect={k=>{setSelectedDate(k);setWeekAnchor(k);setMonthOpen(false)}} onMove={k=>{setSelectedDate(k);setWeekAnchor(k)}}/>:<div className="calendar-week no-scrollbar">{week.map(key=>{const d=parseJalaliKey(key),active=key===selectedDate,count=tasksForDay(tasks,key).length;return <button key={key} className={active?'selected':''} onClick={()=>setSelectedDate(key)}><span>{dayName(key).replace('‌',' ')}</span><strong>{toPersianDigits(d?.jd??'')}</strong><i>{count?toPersianDigits(count):''}</i></button>})}</div>}
  <button className="calendar-note"><Plus/><span>یادداشت روزانه</span><small>یک نکته برای خودت بنویس</small></button>
  <div className="calendar-summary"><div><BookOpen/><span>زمان مطالعه</span><strong>{durationLabel(total)}</strong></div><div><CheckCircle2/><span>انجام‌شده</span><strong>{toPersianDigits(done)} از {toPersianDigits(dayTasks.length)}</strong></div><div><Flame/><span>تمرکز روز</span><strong>{dayTasks[0]?.subjectName??'آزاد'}</strong></div></div>
  <div className="calendar-section-title"><div><span>فعالیت‌ها</span><small>{formatJalaliKeyWithWeekday(selectedDate)}</small></div><button onClick={()=>setFormOpen(true)}><Plus/> ثبت فعالیت جدید</button></div>
  {!dayTasks.length?<div className="calendar-zero"><CalendarDays/><strong>این روز هنوز خالیه</strong><span>اولین فعالیت را بچین، بقیه‌اش راه می‌افتد.</span><button onClick={()=>setFormOpen(true)}>ساخت اولین فعالیت</button></div>:<div className="calendar-activities">{dayTasks.map(task=>{const end=minutesToTime(timeToMinutes(task.startTime)+task.durationMinutes);return <article key={task.id} style={{'--task-color':task.color??'#6D5DFB'} as React.CSSProperties}><button className="calendar-check" onClick={()=>onToggleTask(task.id)}>{task.isCompleted?<CheckCircle2/>:<Circle/>}</button><div className="calendar-activity-main"><div className="calendar-activity-top"><span>{task.activityType==='class'?'کلاس درسی':task.activityType==='other'?'فعالیت':'گزارش مطالعه'}</span><button onClick={()=>setMenu(menu===task.id?null:task.id)}><MoreHorizontal/></button></div><h3 className={task.isCompleted?'done':''}>{task.chapter||task.subjectName}</h3>{task.chapter&&<p>{task.subjectName}</p>}<div className="calendar-activity-meta"><span><Clock3/> {toPersianDigits(task.startTime)} تا {toPersianDigits(end)}</span>{task.questionCount?<span><FileText/> {toPersianDigits(task.questionCount)} سوال</span>:null}</div>{menu===task.id&&<div className="calendar-item-menu"><button onClick={()=>onStartFocus(task.subjectName)}><Play/> شروع تمرکز</button><button className="danger" onClick={()=>onDeleteTask(task.id)}><Trash2/> حذف فعالیت</button></div>}</div></article>})}</div>}
  {formOpen&&<ActivityForm subjects={subjects} dateStr={selectedDate} onClose={()=>setFormOpen(false)} onSave={(data,start)=>{onAddTask(data);setFormOpen(false);if(start)onStartFocus(data.subjectName)}}/>}
 </section>
};

const MonthPicker:React.FC<{year:number;month:number;selected:string;tasks:TaskItem[];onSelect:(k:string)=>void;onMove:(k:string)=>void}>=({year,month,selected,tasks,onSelect,onMove})=>{const first=jalaliKeyToDate(`${year}/${String(month).padStart(2,'0')}/01`),offset=first?(first.getDay()+1)%7:0,days=month<=6?31:month<=11?30:29,cells=Array.from({length:offset+days},(_,i)=>i<offset?null:i-offset+1);const move=(delta:number)=>{let y=year,m=month+delta;if(m===13){y++;m=1}if(m===0){y--;m=12}onMove(`${y}/${String(m).padStart(2,'0')}/01`)};return <div className="month-picker"><div className="month-picker-nav"><button onClick={()=>move(1)}><ChevronRight/></button><strong>{PERSIAN_MONTHS[month-1]}</strong><button onClick={()=>move(-1)}><ChevronLeft/></button></div><div className="month-weekdays">{['ش','ی','د','س','چ','پ','ج'].map(d=><span key={d}>{d}</span>)}</div><div className="month-grid">{cells.map((day,i)=>{if(!day)return <span key={i}/>;const key=`${year}/${String(month).padStart(2,'0')}/${String(day).padStart(2,'0')}`;return <button key={key} className={key===selected?'selected':''} onClick={()=>onSelect(key)}>{toPersianDigits(day)}{tasks.some(t=>t.dateStr===key)&&<i/>}</button>})}</div></div>};

const ActivityForm:React.FC<{subjects:SubjectItem[];dateStr:string;onClose:()=>void;onSave:(d:Omit<TaskItem,'id'>,start:boolean)=>void}>=({subjects,dateStr,onClose,onSave})=>{
 const [step,setStep]=useState(1),[type,setType]=useState<ActivityType>('study'),[subjectId,setSubjectId]=useState(''),[subjectSearch,setSubjectSearch]=useState(''),[chapter,setChapter]=useState(''),[chapterSearch,setChapterSearch]=useState(''),[mode,setMode]=useState<TimeMode>('range'),[start,setStart]=useState('08:30'),[end,setEnd]=useState('09:30'),[duration,setDuration]=useState(60),[more,setMore]=useState(false),[resource,setResource]=useState(''),[report,setReport]=useState('درسنامه و تست'),[qType,setQType]=useState<'test'|'written'>('test'),[qCount,setQCount]=useState(''),[notes,setNotes]=useState(''),[color,setColor]=useState(COLORS[0]),[error,setError]=useState('');
 const subject=subjects.find(s=>s.id===subjectId), chapters=subject?(CHAPTERS[subject.name]??GENERIC):[], filteredSubjects=subjects.filter(s=>s.name.includes(subjectSearch.trim())),filteredChapters=chapters.filter(c=>c.includes(chapterSearch.trim()));
 const save=(startNow:boolean)=>{if(!subject){setStep(1);return setError('یک درس انتخاب کن.')}if(!chapter){setStep(2);return setError('فصل یا عنوان فعالیت را انتخاب کن.')}let minutes=duration;if(mode==='range'){minutes=timeToMinutes(end)-timeToMinutes(start);if(minutes<=0){setStep(3);return setError('زمان پایان باید بعد از شروع باشد.')}}onSave({subjectId:subject.id,subjectName:subject.name,activityType:type,chapter,dateStr,startTime:normalizeTime(start),durationMinutes:Math.max(5,minutes),isCompleted:false,notes:notes.trim()||undefined,resource:resource.trim()||undefined,reportType:type==='study'?report:undefined,questionType:type==='study'?qType:undefined,questionCount:qCount?Math.max(0,Number(qCount)):undefined,color,loggedMinutes:0},startNow)};
 return <div className="activity-form-shell" role="dialog" aria-modal="true"><div className="activity-form"><header><button onClick={onClose}><X/></button><div><span>فعالیت جدید</span><strong>{formatJalaliKey(dateStr)}</strong></div><div className="form-step">{toPersianDigits(step)}</div></header><div className="form-progress"><i style={{transform:`scaleX(${step/3})`}}/></div><main>
 {step===1&&<div className="form-panel"><div className="form-intro"><span><Layers3/></span><div><h2>چه فعالیتی؟</h2><p>نوع فعالیت و درس را انتخاب کن.</p></div></div><div className="activity-tabs"><button className={type==='study'?'active':''} onClick={()=>setType('study')}><BookOpen/>گزارش مطالعه</button><button className={type==='class'?'active':''} onClick={()=>setType('class')}><GraduationCap/>کلاس درسی</button><button className={type==='other'?'active':''} onClick={()=>setType('other')}><Sparkles/>سایر فعالیت‌ها</button></div><label className="form-label">عنوان درس</label><div className="search-field"><Search/><input value={subjectSearch} onChange={e=>setSubjectSearch(e.target.value)} placeholder="جست‌وجوی درس..."/></div><div className="subject-list">{filteredSubjects.map(s=><button key={s.id} className={subjectId===s.id?'selected':''} onClick={()=>{setSubjectId(s.id);setChapter('');setError('')}}><i style={{backgroundColor:s.color}}/><span>{s.name}</span>{subjectId===s.id&&<Check/>}</button>)}</div></div>}
 {step===2&&<div className="form-panel"><div className="form-intro"><span><BookOpen/></span><div><h2>{type==='other'?'عنوان فعالیت':'کدام فصل؟'}</h2><p>{subject?.name}</p></div></div>{type==='other'?<div className="free-chapter"><label className="form-label">عنوان فعالیت</label><input value={chapter} onChange={e=>setChapter(e.target.value)} placeholder="مثلاً جلسه مشاوره"/></div>:<><div className="search-field"><Search/><input value={chapterSearch} onChange={e=>setChapterSearch(e.target.value)} placeholder="جست‌وجوی فصل..."/></div><div className="chapter-list">{filteredChapters.map((c,i)=><button key={c} className={chapter===c?'selected':''} onClick={()=>{setChapter(c);setError('')}}><span>{toPersianDigits(i+1)}</span><strong>{c}</strong>{chapter===c&&<CheckCircle2/>}</button>)}<button onClick={()=>{const v=window.prompt('نام مبحث را وارد کن');if(v?.trim())setChapter(v.trim())}}><span><Plus/></span><strong>مبحث دلخواه</strong></button></div></>}</div>}
 {step===3&&<div className="form-panel"><div className="form-intro"><span><Clock3/></span><div><h2>زمان‌بندی</h2><p>بازه‌ی مطالعه را دقیق مشخص کن.</p></div></div><div className="time-mode"><button className={mode==='range'?'active':''} onClick={()=>setMode('range')}>بازه زمانی</button><button className={mode==='duration'?'active':''} onClick={()=>setMode('duration')}>حجم زمانی</button></div><div className="time-fields"><label><span>زمان شروع</span><input type="time" value={start} onChange={e=>setStart(e.target.value)}/></label>{mode==='range'?<label><span>زمان پایان</span><input type="time" value={end} onChange={e=>setEnd(e.target.value)}/></label>:<label><span>مدت مطالعه</span><select value={duration} onChange={e=>setDuration(Number(e.target.value))}>{[30,45,60,75,90,120,180].map(m=><option key={m} value={m}>{durationLabel(m)}</option>)}</select></label>}</div><button className="more-settings" onClick={()=>setMore(v=>!v)}><span><MoreHorizontal/> تنظیمات بیشتر</span><ChevronDown className={more?'rotated':''}/></button>{more&&<div className="more-fields"><label><span>منبع درسی</span><input value={resource} onChange={e=>setResource(e.target.value)} placeholder="مثلاً کتاب درسی"/></label>{type==='study'&&<><label><span>نوع گزارش</span><select value={report} onChange={e=>setReport(e.target.value)}><option>درسنامه و تست</option><option>مرور و جمع‌بندی</option><option>آزمون و تحلیل</option><option>حل تمرین</option></select></label><div className="question-row"><label><span>نوع سوال</span><select value={qType} onChange={e=>setQType(e.target.value as 'test'|'written')}><option value="test">تستی</option><option value="written">تشریحی</option></select></label><label><span>تعداد سوال</span><input type="number" min="0" value={qCount} onChange={e=>setQCount(e.target.value)} placeholder="۰"/></label></div></>}<label><span>توضیحات</span><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="جزئیات مهم..."/></label><div><span className="field-caption"><Palette/> رنگ فعالیت</span><div className="color-picker">{COLORS.map(c=><button key={c} style={{backgroundColor:c}} className={color===c?'selected':''} onClick={()=>setColor(c)}>{color===c&&<Check/>}</button>)}</div></div></div>}</div>}
 {error&&<div className="form-error">{error}</div>}</main><footer>{step>1?<button className="back" onClick={()=>{setStep(s=>s-1);setError('')}}><ChevronRight/> قبلی</button>:<span/>}{step<3?<button className="next" onClick={()=>{if(step===1&&!subject)return setError('یک درس انتخاب کن.');if(step===2&&!chapter)return setError('فصل یا عنوان فعالیت را انتخاب کن.');setError('');setStep(s=>s+1)}}>ادامه <ChevronLeft/></button>:<div className="save-actions"><button className="timer-save" onClick={()=>save(true)}><TimerReset/> ذخیره و شروع</button><button className="save" onClick={()=>save(false)}><Check/> تایید و ذخیره</button></div>}</footer></div></div>
};
